### ISSUE TITLE
Suggestion: use Map

### ISSUE THREAD

**Issue by xogeny** [node-cache/node-cache#165]
I took a peak at the TypeScript port.  Could you please consider using `Map` instead of just a pure object for data?  It will help you avoid various pitfalls associated with objects and it maps (no pun intended) perfectly onto the domain of what you are trying to do.

Just a suggestion...

PS - I do a lot of TypeScript work, so happy to provide feedback or code reviews.

**Comment by erdii** [comment]
Hey again :) That's a nice idea!

Will investige if Map is supported in all Node versions we do, but currently I don't have time to finish the typescript port (tests and features that were added since the port forked are still missing), soooooo this is a message to everyone out there: PRs to finish the typescript port are highly welcome! :blush:
